### ISSUE TITLE
Repeated information

### ISSUE THREAD

**Issue by sha0coder** [DanMcInerney/net-creds#16]
Working with big pcap files, there are a lot of repeated output, 
It will very useful not show repeated data.

**Comment by DanMcInerney** [comment]
This was a design decision but not one I'm married to. Just like I kept in the reporting of NTLM hashes that are missing the challenge and thus uncrackable, I liked knowing how much traffic and credentials were traveling across the network even if they were repeats. I believe the reporting in the log file is not repetitious and I think users should generally use the log file for actual credential harvesting rather than the live output so for the time being, at least, I'm going to keep the live output really live.
