### ISSUE TITLE
Implement HTTPS

### ISSUE THREAD

**Issue by TheSph1nx** [DanMcInerney/net-creds#27]
Sniffing HTTPs authentications.

**Comment by Aholicknight** [comment]
This woudent be possible since `HTTPS` is encrypted.

**Comment by TheSph1nx** [comment]
I know but what about Zeus then?

**Comment by Aholicknight** [comment]
@SPB-Production I dont know what you mean by `Zeus`. Please be more specific.

**Comment by TheSph1nx** [comment]
Zeus I mean the botnet , the agent can sniff https traffic .

**Comment by TrevorRowe123** [comment]
Zeus sniffs HTTPS traffic on the client, before the outgoing traffic is encrypted, and after the inbound traffic is decrypted.  It isn't able to actually decrypt traffic on its own.

**Comment by DanMcInerney** [comment]
@SPB-Production, @werro123 is right.

**Comment by TheSph1nx** [comment]
I know how it works but why don't trying to implement a method to decode the traffic before leaving the machine ...

**Comment by DanMcInerney** [comment]
That'd be pretty cool, but I feel the main purpose of this script is for
parsing pcaps. It can be run live, but it quickly eats all the cpu.
Additionally, capturing traffic prior to encryption is not a trivial task.
There's a tool called netripper that does it but to implement that
functionality in a simple python script like this would be a major
undertaking that I don't feel like doing right now especially since I'm
working on icebreaker and some other stuff for the foreseeable future.

I like the thought though, would be a neat feature. Maybe I'll try
something like that in the future.

**Comment by TheSph1nx** [comment]
@DanMcInerney Yes don't worry , I asked that because I tryed to implement that in python and other languages but i can't a find an elegant solution so i thought maybe you know something more about it (I needed https decryption for my project spacenet). I know about netripper but i've found some trouble working with it so i thought was better working on something else . Anyway thanks for the answers , good work for icebreaker ;) .
